#!/bin/sh
# Copyright (c) 2002 SuSE GmbH Nuernberg, Germany.  All rights reserved.
#
# Author: Stefan Dirsch, 2002
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published
# by the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software Foundation,
# Inc., 675 Mass Ave, Cambridge MA 02139, USA.

# Check for sound 3D requirements and pops up a window to
# abort/continue, if there are problems and starts program
# 
# Required programs:
# - ChechFor3DLibs
# - Check4SoundLibs
# - CheckHardware

if [ $# -eq 0 ]; then
  echo "Usage: GameWrapper <command> [options]"
  exit 1
fi

SOUND=""
DREID=""
COMMAND=$1

Chech4SoundLibs $COMMAND && SOUND="--sound"
ChechFor3DLibs  $COMMAND && DREID="--3d"

#echo "CheckHardware $SOUND $DREID $*"
CheckHardware $SOUND $DREID $*

exit 0

