#/.../
# Copyright (c) 2001 SuSE GmbH Nuernberg, Germany. All rights reserved.
# Author: Marcus Schaefer <sax@suse.de>, 2001
#
# Makefile for SaX2 po file generation
# X-Server configuration program
#
all:
	./.locale

clean:
	rm -f *.pot
	find -name CheckHardware.*.po | xargs rm -f
	find -name CheckHardware.mo | xargs rm -f
